### ISSUE TITLE
"this" context doesn't properly flow to arrow functions

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/rhino#2]
example of not working code
```js
const Note = function(x, y) {
    this.dragging = false

    this.top = UIBlock(new Color(0.9019, 0.7255, 0.0157))
        .setX(new PixelConstraint(1))
        .setY(new PixelConstraint(1))
        .setWidth(new SubtractiveSizeConstraint(new FillConstraint(), new PixelConstraint(1)))
        .setHeight(new PixelConstraint(15))
        .onMouseClick(() => {
            this.dragging = true
        })
}
```
when MouseAction (set by onMouseClick) is called by java in Elementa, "this" from the Note object does not get passed through to the arrow function.

Example of working code (click is called from js not from java)
```js
const TestObject = function() {
    this.dragged = false
    this.click = () => {
        this.dragged = true
        print(this.dragged)
    }
}

new TestObject().click()
```

**Comment by FalseHonesty** [comment]
Yeah, this is due to commit aee2a777ff708e6abc862a706f204f770b30a9b1, which allowed arrow functions to be passed at all. Obviously this implementation was somewhat short-sighted and will need more thorough investigation.
